// 곡 및 채보 데이터
if (typeof SONG_DATABASE === 'undefined') window.SONG_DATABASE = [];

SONG_DATABASE.push({
  id: "anzs_raid",
  title: "안즈스 레이드 BGM",
  bgm: "audio/song.mp3",
  bpm: 120,
  keys: 4,
  difficulty: "Lv.3 하드",
  speed: 480,
  notes: [
    { time: 1.25, lane: 3 },
    { time: 1.25, lane: 1 },
    { time: 1.25, lane: 0 },
    { time: 1.25, lane: 2 },
    { time: 1.5, lane: 1 },
    { time: 1.5, lane: 3 },
    { time: 1.5, lane: 2 },
    { time: 1.5, lane: 0 },
    { time: 1.75, lane: 3 },
    { time: 1.75, lane: 1 },
    { time: 1.75, lane: 2 },
    { time: 1.75, lane: 0 },
    { time: 2, lane: 3 },
    { time: 2, lane: 1 },
    { time: 2, lane: 2 },
    { time: 2, lane: 0 },
    { time: 2.5, lane: 3, type: "gold" },
    { time: 2.5, lane: 2, type: "gold" },
    { time: 2.5, lane: 1, type: "gold" },
    { time: 2.5, lane: 0, type: "gold" },
    { time: 2.75, lane: 3, type: "gold" },
    { time: 2.75, lane: 2, type: "gold" },
    { time: 2.75, lane: 1, type: "gold" },
    { time: 2.75, lane: 0, type: "gold" },
    { time: 3.5, lane: 3 },
    { time: 3.5, lane: 2 },
    { time: 3.5, lane: 1 },
    { time: 3.5, lane: 0 },
    { time: 4, lane: 3 },
    { time: 4, lane: 2 },
    { time: 4, lane: 1 },
    { time: 4.25, lane: 0 },
    { time: 4.75, lane: 3 },
    { time: 4.75, lane: 0 },
    { time: 5, lane: 2 },
    { time: 5, lane: 0 },
    { time: 5.25, lane: 1 }
  ]
});
